### ISSUE TITLE
scroll.js, navbar, API ref

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes-sigs/reference-docs#104]
For some time now, there appears to be a scrolling/navigation issue in the API ref.
After selecting some item in the left nav list, the selected section is displayed in the main page.
However, the left navigation does not remain on the selected item.
Instead, the nav. list displays another unrelated item, such as:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#watch-list-csinode-v1beta1-storage-k8s-io.

**Comment by tengqm** [comment]
Looks like the watch list node for CSINode resource is causing some problems. Will investigate.

**Comment by kbhawkey** [comment]
@tengqm , Check out config.yaml, lines 84 -86. Is the version correct? The 1.17 API reference link in the left nav shows `v1beta1`.
Would it be possible to auto-generate config.yaml from swagger.json? Manually maintaining this list seems error prone.

```
 - name: CSINode
      version: v1
      group: storage
```

**Comment by tengqm** [comment]
@kbhawkey Good spot. The current API reference doc is incorrect. I hope when https://github.com/kubernetes/website/pull/18067 is in, the navigation error will go away.

Generating config.yaml would be very difficult if possible at all. We need  to distinguish the top level resources (e.g. `Pod`) from the nested resources (e.g. `PodSpec`, `CSIDriver`). Then we need to collect all versions of a particular resource, pick the latest version and leave the others as "old versions". For new resource types added, we need to find a "group" for it...

**Comment by kbhawkey** [comment]
Just checked generated API reference in PR 18067. The left navigation appears to be fixed.
