### ISSUE TITLE
API ref, navbar text strings

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes-sigs/reference-docs#105]
**Problem**:
The strings in the API reference left navbar list exceed the fixed display area.

**Solution**:
Possibly increase the width for this component or modify the
overflow-x field to `auto`.
Update stylesheet.css.

```
#sidebar-wrapper {
    display: block;
    height: 100%;
    width: 20%;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: whitesmoke;
    border-right: 2px solid slategrey;
    overflow-x: hidden;
    padding-top: 60px;
}
```

**Comment by tengqm** [comment]
Em.. good idea.
I'm also thinking if we should allow the left nav bar to be toggled on/off.
