### ISSUE TITLE
api ref: style, container or container-fluid

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes-sigs/reference-docs#123]
The class attribute for the html body was changed to use the `container` attribute over the `container-fluid` attribute.
This change prevents the text from the main page "overflowing", but squashes the text in the
individual table fields. There is also unused page space on the right hand side (viewing on Ubuntu laptop smallish screen).

https://github.com/kubernetes-sigs/reference-docs/blob/master/gen-apidocs/generators/html.go#L616

**Comment by tengqm** [comment]
/close
This seems resolved. Can reopen if it bubbles up again.
