### ISSUE TITLE
Work out a new way to get the API version

### ISSUE THREAD

**Issue by tengqm** [kubernetes-sigs/reference-docs#127]
With https://github.com/kubernetes/kubernetes/pull/84654 approved and back ported to many versions, we won't be able to tell which version a API spec is for. This is really sad thing. We will need a different way to get the version and make sure we are not making mistakes ...

**Comment by kbhawkey** [comment]
I read through kubernetes/kubernetes/#84654. Thanks for pointing that out.
I asked few questions and basically, you can run the API server and `fetch` the spec or:

```
The easiest way to get the generated spec for a tagged release version is to fetch the file at that tag, e.g. git show v1.16.0:./api/openapi-spec/swagger.json

   Q: What if I want to build the docs before the release is released -- just to check that things actually build and dependencies are checked, etc.? What branch could be used?

The release branch, e.g. git show release-1.16:./api/openapi-spec/swagger.json

We have a verification script that ensure the definitions/schemas/operations/etc in the committed file matches the output of the server at that sha.

```
The spec gen'ed from the API server is complete, the static tagged/release spec is missing the info.version field.

**Comment by kbhawkey** [comment]
So, I would imagine that a copy of the spec could be saved in a versioned dir or obtained to match the release, but not saved in a base or common location (always versioned).

**Comment by tengqm** [comment]
Yes. "versioned config" was something nice to have but now because something desirable.

**Comment by kbhawkey** [comment]
@tengqm ,
Thinking some more on versioning.
I plan to update and test the import script and directory setup script setting the K8S_RELEASE var as the branch tag. The current string is close, but the script would be improved if this string matched.
The tag can be used to identify the swagger file (change the updateapisepc target).
The swagger file could be saved to a versioned dir, as it is now, and copied to the <generator_base>/config directory to use in the generation process. Should the versioned directory structure change from, for example `v1_17` to `v_1_17_0` (include patch number to match the tag that is required to get the correct version of the api spec)? I am not in favor of saving a copy of the release* version of the file. What do you think?

Possible  K8S_RELEASE values:
v1.17.0
release-1.16
release-1.18

Previous K8S_RELEASE values:
1.17
1.16

**Comment by tengqm** [comment]
@kbhawkey Since the upstream make change the API spec in a release branch, pinning to branch names is obviously not a solution. We should use tags, e.g. `1.16.1`, `1.17.0` etc.
I am not anticipating a strong requirement for documenting all the patch versions from `1.16.0` to `1.16.4` or from `1.14.0` to `1.14.10`. So maybe serving `1.16.0` and `1.17.0` etc would be sufficient. We are not notified automatically when `1.16.2` build is out or when `1.14.11` is out, so tracking the "latest" patch version for each release is impractical either.

I'd suggest we use the shortest string as the K8S_RELEASE value and let the scripts derive tag names, dir names from it. Take the 1.17 release for example, we use `1.17` as the value for K8S_RELEASE. The scripts then decides to checkout the `swagger.json` from `$K8S_RELEASE.0` tag, into a versioned dir named `$K8S_RELEASE`. The ref generator can detect the `$K8S_RELEASE` variable and check if there is a swagger JSON in the versioned dir and then generates the docs if so. The generator will output the `$K8S_RELASE.0` string as the API version, rather than parsing the swagger spec.

**Comment by kbhawkey** [comment]
@tengqm , Yes, I am suggesting tags over branch names. Is there be a requirement to build from the `release-1.17` branch? It would certainly be easier and more predictable to just build docs that match a tagged release (and nothing in between).
I agree that documenting patch versions is unnecessary at this time.
I like your idea about pulling the version string from the K8S_RELEASE variable.

**Comment by tengqm** [comment]
I think this can be closed. The propose solution should work well to address this.
