### ISSUE TITLE
Tweak the page content style

### ISSUE THREAD

**Issue by tengqm** [kubernetes-sigs/reference-docs#136]
The current 'page-content container' class assigned to the right (main) panel needs some  tweaking:

- The current style is wasting some real estate on screen.
- We'd better add some attributes to the tables so that the property name column is not too narrow (xref: kubernetes/website#19757)

**Comment by Arhell** [comment]
@tengqm 
Hello, please see the solution
https://github.com/kubernetes/website/pull/19771
---------------------------------------------------------------------------------
https://deploy-preview-19771--kubernetes-io-master-staging.netlify.com/docs/reference/generated/kubernetes-api/v1.17/

**Comment by Arhell** [comment]
ping @tengqm 
#137

**Comment by tengqm** [comment]
Related: https://github.com/kubernetes/website/issues/19795
