### ISSUE TITLE
Generating reference docs for kube-scheduler

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/reference-docs#138]
Ref: kubernetes/kubernetes#88919

I've successfully been able to generate docs for kube-scheduler APIs using https://github.com/ahmetb/gen-crd-api-reference-docs

Could anyone give me guidance on how to integrate it in this repo?

In particular, is there any template I can use?

**Comment by kbhawkey** [comment]
@alculquicondor , Great! **The release is tommorow**.
Did you generate a single page HTML file?
Instead, you could add a page to k8s/website (or include this reference in one of the scheduler pages) and include the html?
I _think_ the release is tomorrow (evening). This may have to go in after the release.
Check out, https://github.com/kubeflow/website/tree/master/gen-api-reference.
The generated page could be copied to the k8s/website _generated dir (https://github.com/kubernetes/website/tree/master/static/docs/reference/generated).
/cc @tengqm @jimangel

**Comment by kbhawkey** [comment]
@alculquicondor , What do you think about adding a new target to the Makefile to:
1. Generate the scheduler API reference
1. Copy the generated reference to the k8s/website directory (like the other references)
1. Include this HTML in a Markdown page under the new scheduler reference directory  (https://kubernetes.io/docs/reference/scheduling/). Will have to see how the page can incorporate a stylesheet.
What do you think? Let me know if I can help.

**Comment by alculquicondor** [comment]
Sorry I missed this response.
Yes, I generated a single page HTML file, but it looks very barebones without a proper template.
Should I include a script in this repository?

> Include this HTML in a Markdown page under the new scheduler reference directory
I'm not sure what you mean here. Like adding an iframe? I was just thinking of copying it to kubernetes/website/tree/master/static/docs/reference/generated

**Comment by kbhawkey** [comment]
> I'm not sure what you mean here. Like adding an iframe? I was just thinking of copying it to kubernetes/website/tree/master/static/docs/reference/generated

Yes, copy to generated location. I am thinking the output could generate a Markdown page or include the generated output in a static Markdown page (that you create).
```
${GEN_DOCS}/gen-crd-api-reference-docs -config ${WEBSITE_ROOT}/gen-api-reference/kubeflow-config.json -template-dir ${GEN_DOCS}/template -api-dir "github.com/kubeflow/tf-operator/pkg/apis/common/v1beta2" -out-file temp_common.md
cat temp_common.md >> ${CONTENT_DIR}/common.md
```


There are a number of Markdown pages in k8s/website that include HTML snippets.
The tables will need some attributes so that they can be styled (bootstrap or some custom style).
Did you check out, the kubeflow->tfjob-api script?

**Comment by alculquicondor** [comment]
I did, but I didn't realize that it could produce markdown as well.
I can generate the files locally, but it might be worth to keep the script in this repository.

**Comment by kbhawkey** [comment]
I don't think so, the script I am referring to concatenates the output with a .md file.
What do I need to generate the scheduler api ref (what is the command you used)? I have a clone of k8s/k8s.

**Comment by kbhawkey** [comment]
Yes, add the script to this repo and update the Makefile so that the generation process can be repeated.

**Comment by alculquicondor** [comment]
```
/junk/src/k8s.io/kube-scheduler ➤ ${GEN_DOCS}/gen-crd-api-reference-docs -api-dir ./config -config ${GEN_DOCS}/example-config.json -template-dir ${GEN_DOCS}/gen-crd-api-reference-docs/
```

Except that you need to remove the blank lines between the api comments and import line in:
`k8s.io/kube-scheduler/config/v1/doc.go`, `k8s.io/kube-scheduler/config/v1alpha1/doc.go` and `k8s.io/kube-scheduler/config/v1alpha2/doc.go`. I'll submit a PR to fix this soon.

**Comment by alculquicondor** [comment]
I got a fix for the tool instead https://github.com/ahmetb/gen-crd-api-reference-docs/pull/19

**Comment by kbhawkey** [comment]
> I got a fix for the tool instead [ahmetb/gen-crd-api-reference-docs#19](https://github.com/ahmetb/gen-crd-api-reference-docs/pull/19)

I am investigating if I can quickly integrate into this repo.

**Comment by kbhawkey** [comment]
@alculquicondor , 
Where do I find the `api-dir`?
## does not work
/tmp/tmpdc3iihix/src/k8s.io/kubernetes/cmd/kube-scheduler/app$ ${GEN_DOCS}/gen-crd-api-reference-docs -api-dir ./config -config ${GEN_DOCS}/example-config.json -template-dir ${GEN_DOCS}/template -out-file temp_common.md

**Comment by kbhawkey** [comment]
Looks like it is here?
k8s.io/kubernetes/pkg/scheduler/apis/config

**Comment by alculquicondor** [comment]
you should clone `k8s.io/kube-scheduler` instead.

**Comment by tengqm** [comment]
For release  1.18, should we use 0.18.0 tag or kubernetes-1.18.0 tag?
I saw client-go is using 0.x.y tags (https://github.com/kubernetes/client-go)

**Comment by kbhawkey** [comment]
Hello @alculquicondor .
After testing how the generation process could work (and viewing the API output), I suggest the following:
Could you propose your ideas about adding a Kube Scheduler API reference to the SIG Docs group (mailing list and Slack channel)? See https://kubernetes.io/docs/contribute/participating/ for information about the mailing list and Slack channel.
That way SIG Docs can provide feedback about the k-s API reference. Your proposal could detail:

- Where should the k-s reference publish in the k8s docs (ready for 1.18 or propose for 1.19)
- What tool should produce the kube-scheduler reference
- How will the reference be maintained
- Is it possible to generate an Open API spec for this reference

In this issue I will write up the steps I took to generate the sample k-s API reference.

/cc @zacharysarah

**Comment by kbhawkey** [comment]
Steps taken to generate sample Kube Scheduler API reference:

1. git clone https://github.com/kubernetes/kubernetes.git
I had a v1.18.0 k8s/k8s branch and copied `src/k8s.io/kube-scheduler` from the k8s/k8s staging area to $GOPATH/src/k8s.io .
1. git clone https://github.com/ahmetb/gen-crd-api-reference-docs. Build a `gen-crd-api-reference-docs` executable.
Set GEN_DOCS variable to location of local `gen-crd-api-reference-docs`.
1. Change directory into $GOPATH/src/k8s.io/kube-scheduler.
1. Run the `gen-crd-api-reference-docs` command (`api-dir` directory is `config` under src/k8s.io/kube-scheduler):
`${GEN_DOCS}/gen-crd-api-reference-docs -api-dir ./config -config ${GEN_DOCS}/example-config.json -template-dir ${GEN_DOCS}/template -out-file ks-ref.md` .

1. Create a Markdown file with basic front matter.

    ```
    ---
    title: Kube Scheduler API Reference
    description: Reference documentation for Kube Scheduler
    weight: 30
    ---
    ```

1. Concatenate the two files (k-s.ref and base file).
1. Use a tool (`sed`) to add class attributes/style attributes to the HTML table elements in generated API ref.
1. Copy to k8s/website. 
1. Alternatively, the reference could be copied to the k8s/website `_generated` directory and incorporated into an existing Markdown page in the reference section.

**Comment by alculquicondor** [comment]
> Is it possible to generate an Open API spec for this reference

Could you explain this further? What's the output of an Open API spec?

**Comment by kbhawkey** [comment]
Hello @alculquicondor ,

I am new to the kube-scheduler API, [k8s.io/kube-scheduler/config](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-scheduler/config).

Is this the relevant KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/wgs/0014-20180707-componentconfig-api-types-to-staging.md#kube-scheduler-changes

Are you familiar with the API Server spec,`https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec/swagger.json`? This spec is used to generate the Kubernetes API reference.

An Open API spec enables you to use a number of tools to generate standard output.

**Comment by alculquicondor** [comment]
Yes, that's a relevant KEP.

> Are you familiar with the API Server `spec,https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec/swagger.json`?

Yes and no. I only know about it because I was looking into how to generate one for kube-scheduler.

I was only able to generate `types_swagger_doc_generated.go` files, but not the `swagger.json` kubernetes/kubernetes#88927
What's that file used for? It is my understanding that `kubernetes-sigs/reference-docs` generates the doc files from a running kube-apiserver. I don't think we want to serve anything from kube-scheduler, as these APIs are only used during configuration time.

**Comment by tengqm** [comment]
Is it fair to say that the so called kube-scheduler API is only about the scheduler configuration?
A full fledged API specification contains operations in addition to type definitions. My anticipation of this is that we will face tons of resource type definitions (aka. CRDs) in the future which doesn't have their dedicated collection of operations. The only operations they support would be CRUD.

**Comment by alculquicondor** [comment]
This particular API (living under `config` folder) is just about configuration, so it doesn't even have CRUD.
We have another API ([extenders](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-scheduler/extender/v1)) which is only about IPC. But for now that one is not OpenAPI.

**Comment by alculquicondor** [comment]
@tengqm do you think I can proceed with the suggestions in https://github.com/kubernetes-sigs/reference-docs/issues/138#issuecomment-605467979

**Comment by tengqm** [comment]
@alculquicondor Sure. Thank you in advance for this contribution.
