### ISSUE TITLE
double hyphen, component tool pages

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes-sigs/reference-docs#152]
Use `&#8208;&#8208;` to replace literal `--` in flag strings.
Alternatively, surround literal in `<span>`.
For further information, see https://github.com/kubernetes/website/issues/20623.

**Comment by tengqm** [comment]
See comments posted to kubernetes/website#20623. It looks like a Hugo issue.

**Comment by kbhawkey** [comment]
Yes, I see. It may be a good idea to update this code anyway.
