### ISSUE TITLE
Separate resource description from list of resource fields, API Markdown reference generator

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes-sigs/reference-docs#188]
Possibly add a separator between the top description and the body of the resource (fields). Otherwise, the two lists blend together.

For example, `StatefulSet`:

```
StatefulSet represents a set of pods with consistent identities. Identities are defined as:

    * Network: A single stable DNS and hostname.

    * Storage: As many VolumeClaims as requested. The StatefulSet guarantees that a given network identity will always map to the same storage identity.
```
https://deploy-preview-23294--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workloads-resources/stateful-set-v1/#StatefulSet

Related to github.com/kubernetes/website#23294

**Comment by feloy** [comment]
@kbhawkey I think you can close this issue which you resolved with #190

**Comment by kbhawkey** [comment]
:eyes:

**Comment by kbhawkey** [comment]
Sure.
/close
