### ISSUE TITLE
add link to inline type definition block from field type, create sub-component

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes-sigs/reference-docs#189]
It can be confusing to read a field definition followed by the expanded type of the field (another list of fields).
Visually it would be helpful to distinguish this content and provide a linked context.
Is it possible to create a new div (or another component) for the nested content?

Partial output from StatefulSet:

```
- **replicas** (int32)

  replicas is the desired number of replicas of the given Template. These are replicas in the sense that they are instantiations of the same Template, but individual replicas also have a consistent identity. If unspecified, defaults to 1.

- **updateStrategy** (StatefulSetUpdateStrategy) --> [Add link to point to in-line content]?

updateStrategy indicates the StatefulSetUpdateStrategy that will be employed to update Pods in the StatefulSet when a revision is made to Template

  <div id="statefulset-update-strategy">
**StatefulSetUpdateStrategy**

StatefulSetUpdateStrategy indicates the strategy that the StatefulSet controller will use to perform updates. It includes any additional parameters necessary to perform the update for the indicated strategy.

  - **updateStrategy.type** (string)

    Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.

  - **updateStrategy.rollingUpdate** (RollingUpdateStatefulSetStrategy)

    RollingUpdate is used to communicate parameters when Type is RollingUpdateStatefulSetStrategyType.

    *RollingUpdateStatefulSetStrategy is used to communicate parameter for RollingUpdateStatefulSetStrategyType.*

  - **updateStrategy.rollingUpdate.partition** (int32)

    Partition indicates the ordinal at which the StatefulSet should be partitioned. Default value is 0.
</div>
```

Is it possible to display multi-nested inline content? I have not come across this yet.

**Comment by kbhawkey** [comment]
@feloy , What do you think about creating a link to the inline content?
An example of this is the `affinity` field in,
https://deploy-preview-23294--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workloads-resources/pod-v1/#scheduling

**Comment by feloy** [comment]
@kbhawkey one way would be to indent lists at every level. For the moment, only one indentation is done, ie:

```
- field1 level 1
- field2 level 1
  - field 1 level 2
  - field 2 level 2
  - field 1 level 3
  - field 2 level 3
  - field 3 level 2
```

We could change to:

```
- field1 level 1
- field2 level 1
  - field 1 level 2
  - field 2 level 2
    - field 1 level 3
    - field 2 level 3
  - field 3 level 2
```

This new presentation would make the text less readable in mobile devices if there are too much nested levels, but it seems the max level is 3 in most cases.

**Comment by kbhawkey** [comment]
Hi @feloy.
It is not clear that more lists (indentation) would help navigate the fields.
I wonder if the name of the field type could be linked to the inline definition or place the definitions in
a separate section at the end of the page?

Current structure of inline content, field lists:
`<field name> (<field type>)` <----- add link here to below
`<field description>`
----> Could add the name of the field type here or provide link of type definition in another location on page?
`<inline field type description>`
`<inline field 1 name> (<inline field 1 type>, linked)`
`<inline field 1 description>`
`<inline field 2 name> (<inline field 2 type>, linked)`
`<inline field 2 description>`

**Comment by kbhawkey** [comment]
There appear to be HTML anchor elements generated in the Markdown files, but the links are not output as HTML?
For example, the `boundObjectRef (BoundObjectReference)`:
https://deploy-preview-23294--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/authentication-resources/token-request-v1/#TokenRequestSpec

**Comment by feloy** [comment]
> There appear to be HTML anchor elements generated in the Markdown files, but the links are not output as HTML?
> For example, the `boundObjectRef (BoundObjectReference)`:
> https://deploy-preview-23294--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/authentication-resources/token-request-v1/#TokenRequestSpec

Yes, I have already added the anchors so we can create external links directly to a field.

You can see an example of such a link at https://deploy-preview-23294--kubernetes-io-master-staging.netlify.app/docs/concepts/configuration/manage-resources-containers/#what-s-next (Read the **ResourceRequirements** API reference)

We will still need to add links from the Type to the definition.
