### ISSUE TITLE
Add comment to all generated files

### ISSUE THREAD

**Issue by tengqm** [kubernetes-sigs/reference-docs#198]
Now and then we receive direct change requests to the generated files.
We should add a comment to all files we generate to indicate that "This is a auto-generated file, please do not change it directly."

**Comment by kbhawkey** [comment]
I think it is helpful to create an informational string in the page footer ("auto-generated by <generator>").
I'm not sure I would go as far as asking not to pursue changes to the page.
If the Api reference resource pages use a custom layout, then we could prevent the display of the link
to the default "edit the page/create PR for page" template? This should be straightforward to change.

**Comment by tengqm** [comment]
Masking out the 'edit/create' buttons would be good.
I'm talking about adding some comments to the generated files in source, so that people will know that this source file is not intended to be manually edited.
For example, https://github.com/kubernetes/website/pull/26035, https://github.com/kubernetes/website/pull/26069,

**Comment by kbhawkey** [comment]
+1

**Comment by jihoon-seo** [comment]
It seems that this issue is resolved by #201, and okay to close.
Is this right? :)

**Comment by tengqm** [comment]
Right. This one can be closed.
/close

**Comment by jihoon-seo** [comment]
Update:
Files like [content/en/docs/reference/command-line-tools-reference/kube-proxy.md](https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/reference/command-line-tools-reference/kube-proxy.md) has the comment
(`The file is auto-generated ...`),

but these files don't, even if these files are generated by the `update-imported-docs.py` script too.

- (Links below are from the PR https://github.com/kubernetes/website/pull/27189, which reflects the updated generated files.)
- [content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm.md](https://raw.githubusercontent.com/kubernetes/website/4ecb418a3baa362ceceff7ff73d0607bc23489fa/content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm.md)
- [content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha.md](https://raw.githubusercontent.com/kubernetes/website/4ecb418a3baa362ceceff7ff73d0607bc23489fa/content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha.md)
- ...

---

@tengqm Could you please take a look again?
Or is this (= 'Don't add the comment to `content/en/docs/reference/setup-tools/kubeadm/generated/*`') an intended behavior of #201?
Sorry for causing confusion!
