### ISSUE TITLE
ScaleStatus and ScaleSpec missing from reference docs.

### ISSUE THREAD

**Issue by bskiba** [kubernetes-sigs/reference-docs#240]
While the autoscaling/v1 Scale is [included in the docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#scale-v1-autoscaling), the autoscaling/v1 ScaleSpec and  autoscaling/v1 ScaleStatus are not.

I checked multiple reference versions (1.21, 1.20, 1,19) and this is true for all of them.

Both types are included in the [swagger.json](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json) file.

@josephburnett

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/ is a deprecated format @bskiba 

However the newer pages within https://kubernetes.io/docs/reference/kubernetes-api/ also don't document this well.

/remove-lifecycle rotten

**Comment by sftim** [comment]
/remove-lifecycle rotten
/reopen

Still a good improvement to make: we could document various subresources better.
