### ISSUE TITLE
Add anchors that would allow linking to items in the generated API reference. Fix search so that it doesn't point to older versions.

### ISSUE THREAD

**Issue by JuliaMongo** [kubernetes-sigs/reference-docs#319]
Please allow linking to items within the generated API reference. For example, we needed a link to publishNotReadyAddresses in the [API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/), but couldn't get it.
Also, there is something with the search for this setting. When searching for it, the results that come up point to the 1.21 version of the API reference, which is not the latest.

See this issue please: https://github.com/kubernetes/website/issues/38033

@tengqm

**Comment by tengqm** [comment]
I'm afraid the generator cannot be smart enough to add the links. The generator only parse the upstream source code comments (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4766-L4773). If you want to improve the description of the field, e.g. adding a link to somewhere, you will need to propose a fix to the kubernetes/kubernetes project. We can then regenerate the reference out of the upstream source code.

**Comment by sftim** [comment]
IMO this _is_ the right place to file the issue, but it's going to need a [KEP](https://github.com/kubernetes/enhancements) and quite a bit of time to make it happen.
