### ISSUE TITLE
Not able join worker node to master node upgraded from v1.25.9 to v1.27.1

### ISSUE THREAD

**Issue by MVD92** [kubernetes-sigs/reference-docs#323]
### What happened?
Recently, I have upgraded cluster from v1.25.9 to v1.27.1 with CRI-O. While joining new node to M1 using kubeadm, Kubelet.crt is not getting generated which in turn is resulting in auto-restart of kubelet service and the node is not able to join the cluster.

### The error is as follows: 
Unfortunately, an error has occurred:
        timed out waiting for the condition

 

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

 

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

I have set systemd cgroup in both config.yaml & crio.conf. 

OS version:
CentOS 7

**Comment by tengqm** [comment]
This doesn't look like a documentation issue.
You may want to follow the instructions given by the `kubeadm` command and check the status of the `kubelet` service.
There is nothing we can do from documentation side.

/close
