### ISSUE TITLE
Kubectl generated docs page contains deprecated flags

### ISSUE THREAD

**Issue by mpuckett159** [kubernetes-sigs/reference-docs#344]
It looks like something has broken for the kubectl docs generation scripting. There is currently at least one flag (I need to investigate further to determine if there are more) for the run subcommand that has been deprecated since 1.24, and is no longer listed in the kubectl help text, or in the kubectl source code. The page can be found [here](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run). I can help out if someone points me to what is generating this page. I also see the yaml [here](https://github.com/kubernetes-sigs/reference-docs/blob/master/kubectl.yaml) listing it, too.

**Comment by tengqm** [comment]
Actually, I'm more inclined to drop the old way to generate the kubectl reference which is based on a docker image that was not maintained.
We could instead generate kubectl reference using the gen-comp command. The output is pure markdown, so it is more in line with the whole k8s website.
I did that and proposed a [PR to k8s website](https://github.com/kubernetes/website/pull/42664). The PR wasn't approved yet. Maybe you can help review it and see if there are things to do there.

**Comment by mpuckett159** [comment]
I'll reach out to Brian to discuss since I've worked with him on some kubectl things. I think he would probably be fine with this, just may not be aware. Thank you for pointing me to this.

**Comment by brianpursley** [comment]
I left a comment on the PR related to this issue.
https://github.com/kubernetes/website/pull/42664#issuecomment-1830637341
