### ISSUE TITLE
NetworkPolicy v1 is out of order in Cluster APIs section

### ISSUE THREAD

**Issue by RTann** [kubernetes-sigs/reference-docs#355]
Reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#networkpolicy-v1-networking-k8s-io

I'm looking at the v1.30 docs (I also saw this is the case for v1.28 and v1.29), and it looks like NetworkPolicy is out of place, as it's placed at the end, and the docs seem to be following an alphabetical order scheme. I'd adjust this, but I'm not sure if the files are generated from elsewhere nor how many versions are worth even addressing. Thanks.

**Comment by RTann** [comment]
Looks like I can just update https://github.com/kubernetes-sigs/reference-docs/blob/master/gen-apidocs/config/config.yaml for v1.30, but I'm not sure how many versions back I should bother. Maybe just the supported versions (v1.27 - v1.30)?

**Comment by RTann** [comment]
I created a PR, but I opted to close it because I do not wish to sign the agreement at this time.

**Comment by Bharadwajshivam28** [comment]
Is someone working on this or can I take a look in this?

**Comment by RTann** [comment]
> Is someone working on this or can I take a look in this?

I don't think anyone has looked into this since, so feel free to take it on

**Comment by Bharadwajshivam28** [comment]
> > Is someone working on this or can I take a look in this?
> 
> I don't think anyone has looked into this since, so feel free to take it on

Hey @RTann can you provide me more information to get started on this issue?

**Comment by RTann** [comment]
> > > Is someone working on this or can I take a look in this?
> > 
> > 
> > I don't think anyone has looked into this since, so feel free to take it on
> 
> Hey @RTann can you provide me more information to get started on this issue?

@Bharadwajshivam28 I don't work on this, so I really have no idea. I tried before, and you can probably just copy what I did before at https://github.com/kubernetes-sigs/reference-docs/pull/360. You'd just need to sign the agreement

**Comment by Bharadwajshivam28** [comment]
> > > > Is someone working on this or can I take a look in this?
> > > 
> > > 
> > > I don't think anyone has looked into this since, so feel free to take it on
> > 
> > 
> > Hey @RTann can you provide me more information to get started on this issue?
> 
> @Bharadwajshivam28 I don't work on this repository, so I really have no idea. I tried before, and you can probably just copy what I did before at #360. You'd just need to sign the agreement

okay
