### ISSUE TITLE
kubectl Reference docs are unusable on mobile

### ISSUE THREAD

**Issue by hjacobs** [kubernetes-sigs/reference-docs#83]
I stumbled over this yesterday during a train travel: I wanted to look up `kubectl` command line flags on my phone (Google Pixel 2) and found that the reference docs are pretty much unusable on mobile right now: 

![EC2atfyWkAIlP9z](https://user-images.githubusercontent.com/510328/63704878-4861dc80-c82c-11e9-9fb8-717f4259e10d.jpg)

The layout seems to be not working in portrait mode on my phone.

My Tweet for context: https://twitter.com/try_except_/status/1165757991158767618

**Comment by nikhita** [comment]
I believe the source of the docs is here: https://github.com/kubernetes-incubator/reference-docs

/cc @tengqm

**Comment by tengqm** [comment]
Ya. The Web UI was not designed for mobile. We are discussing whether/when to migrate to pure markdown doc generation for kubectl.

**Comment by sftim** [comment]
We have https://kubernetes.io/docs/reference/kubectl/ which should be much more usable

/close
