### ISSUE TITLE
modify http-cache, kubectl, gen-compdocs

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes-sigs/reference-docs#99]
With Kubernetes v1.17, kubectl `cache-dir` default value contains a resolved value for $HOME.
Substitute resolved value with `$HOME`.
-cache-dir Default: "$HOME/.kube/http-cache"

**Comment by tengqm** [comment]
Do you mean the `$HOME` one? I don't think we get a chance to see the special character. The default value was already set to current user's home directory before we know its existence.

**Comment by kbhawkey** [comment]
Yes, `$HOME`. This issue is new with v1.17. Is it possible to change in k8s/k8s?

**Comment by tengqm** [comment]
@kbhawkey I'm not optimistic about this. See the code here: 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L57

and where it is referenced before we check the config structure:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L326

**Comment by tengqm** [comment]
xref: https://github.com/kubernetes/website/pull/18010#pullrequestreview-328878902

**Comment by kbhawkey** [comment]
> @kbhawkey I'm not optimistic about this. See the code here:
> 
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L57
> 
> and where it is referenced before we check the config structure:
> 
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L326

OK. Thanks for clarifying.
Possibly clean up content in gen'ed table:

```
<tr>
      <td colspan="2">--cache-dir string&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Default: "/home/username/.kube/http-cache"</td>
    </tr>
    <tr>
      <td></td><td style="line-height: 130%; word-wrap: break-word;">Default HTTP cache directory</td>
    </tr>
```
